### ISSUE TITLE
issue of "Could not initialize class"

### ISSUE THREAD

**Issue by SteveLuo8** [academyofdata/cassandra-zeppelin#1]
I ran the single node docker-compose. but i got the following error when running:
1
%cassandra
DESCRIBE KEYSPACE

java.lang.NoClassDefFoundError: Could not initialize class org.apache.zeppelin.cassandra.DisplaySystem$NoResultDisplay$
	at org.apache.zeppelin.cassandra.EnhancedSession.<init>(EnhancedSession.scala:40)
	at org.apache.zeppelin.cassandra.InterpreterLogic.<init>(InterpreterLogic.scala:98)
	at org.apache.zeppelin.cassandra.CassandraInterpreter.open(CassandraInterpreter.java:231)
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.open(LazyOpenInterpreter.java:70)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:491)
	at org.apache.zeppelin.scheduler.Job.run(Job.java:175)
	at org.apache.zeppelin.scheduler.ParallelScheduler$JobRunner.run(ParallelScheduler.java:162)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

2 %cassandra
help

Got the same error

**Comment by ranglang** [comment]
same error

**Comment by ranglang** [comment]
fix it by add  scala-reflect jar to plugin dir.

**Comment by Susanalz** [comment]
Hello, How did you finally solve this problem? I have the same error.
